project:
  type: website
  pre-render: generate.r
  output-dir: docs

website:
  title: "MRMN"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - background.qmd
      - table.qmd
      - r-universe.qmd
      - submit.qmd
      - text: "Related"
        href: related.qmd
      - icon: github
        href: https://github.com/mr-methods-network/mr-methods-network.github.io
  repo-url: https://github.com/mr-methods-network/mr-methods-network.github.io
  repo-actions: source
  repo-branch: main
  site-url: https://mr-methods-network.github.io/

format:
  html:
    theme: journal
    css: styles.css
