project:
  type: website
  pre-render: generate.r
  output-dir: docs

website:
  title: "OpenMR project"
  navbar:
    right:
      - index.qmd
      - submit.qmd
      - software.qmd
      - background.qmd
      - icon: github
        href: https://github.com/open-mr-project/open-mr-project.github.io
  repo-url: https://github.com/open-mr-project/open-mr-project.github.io
  repo-actions: source
  repo-branch: main
  site-url: https://open-mr-project.github.io/

format:
  html:
    theme: journal
    css: styles.css
