project:
  type: website
  pre-render: generate.r

website:
  title: "MRMN"
  navbar:
    right:
      - background.qmd
      - table.qmd
      - simulations.qmd
      - blog.qmd
      - submit.qmd
      - icon: github
      - icon: twitter
        href: https://twitter.com
        href: https://github.com/mr-methods-network/mr-methods-network.github.io
format:
  html:
    theme: journal
    css: styles.css



